### ISSUE TITLE
secret看起来没有用

### ISSUE THREAD

**Issue by nmuxiang** [getnas/aria2#1]
在docker-compose.yml里设置了secret，但是aria2.conf里看起来没有，请问修复了吗

**Comment by yuhr123** [comment]
修复了，重新拉取一下最近的镜像再试下。
之前的脚本里面忘了添加换行，结果secret被附加到了BT-tracker后面。

**Comment by nmuxiang** [comment]
最新镜像就是我拉取的那个，要不你再看看。

**Comment by yuhr123** [comment]
你要把原来的配置文件删除掉，重新部署一下，因为配置文件已经被拷贝到宿主机映射的目录上了。
